### PR TITLE
Rework of ReversibleGraphNet

### PR DESCRIPTION
**Pull request by fdraxler**
Main algorithm is `topological_order` that brings all nodes in a graph in an order, aka in a sorted list. It ensures that latter nodes in this list have all inputs executed.

Tasks:
- [x] Nodes instantiate modules directly.
- [x] Buffer-free evaluation
- [x] Return a tuple of output, jacobian
- [x] Rename to GraphINN
- [x] Embed GraphINN into GraphINNs (output must be tuple, output_dims returns something sensible)
- [x] Embed SequenceINN into GraphINNs  (output must be tuple, output_dims returns something sensible)
- [x] intermediate_outputs=True => Jacobian dict?
- [x] Pass tests

### CODE REVIEW

**Comment by fdraxler** [comment]
- [ ] Nodes instantiate modules directly.
- [ ] Buffer-free evaluation
- [ ] Return a tuple of output, jacobian
- [ ] Rename to GraphINN
- [ ] Embed GraphINN into GraphINNs (output must be tuple, output_dims returns something sensible)
- [ ] Embed SequenceINN into GraphINNs  (output must be tuple, output_dims returns something sensible)
- [ ] intermediate_outputs=True => Jacobian dict?

**Comment by psteinb** [comment]
You may also consider, if the unit tests pass - as you altered the internal implementation (only/mostly). `test_conditioning.py`
might be a good start.

**Comment by ardizzone** [comment]
Can this be merged already? I think the tests won't pass because the new modules aren't merged yet, and the new module's tests won't pass because the new RGN isn't merged yet.

**Comment by psteinb** [comment]
Then the answer is yes, I suppose.

**Comment by fdraxler** [comment]
All tests pass except some numerical checks with insufficient accuracy (but numbers are close, so might have been a problem beforehand)
Jacobian of GMM appears incorrectly shaped

**Comment by ardizzone** [comment]
Splendid! The GMM is someone else's task to fix! You can do the honor of hitting the "MERGE" button!

**Pull request merged**
