### PR TITLE
potrf is now called cholesky

### PR DESCRIPTION
**Pull request by fdraxler**

### CODE REVIEW

**Comment by fdraxler** [comment]
Appears like this is not the fix for #22. Why not use torch.det(M) to compute the Jacobian instead in `fixed_transforms.py`?

**Comment by Johnson-yue** [comment]
> Appears like this is not the fix for #22. Why not use torch.det(M) to compute the Jacobian instead in `fixed_transforms.py`?

in pytorch==1.0.0 , torch.potrf() default upper=True, and in pytorch>=1.2.0 torch.cholesky() default upper=False, so you should don't use default between the different pytorch version

**Comment by ardizzone** [comment]
> Appears like this is not the fix for #22. Why not use torch.det(M) to compute the Jacobian instead in `fixed_transforms.py`?

even if `log(det(M))` is a resonable number, if you compute it that way for matrices > e.g. 500x500, you usually get `det(M) = INF`, and then `log(INF)` is still `INF`. That is why we did it in the roundabout way in the first case, where the problem doesn't occur (because `sum(log(s))` is well defined and `log(prod(s))` is `INF`).

I can't merge the PR for now, but we will work something out this week.

**Comment by fdraxler** [comment]
There is `torch.logdet`

**Comment by ardizzone** [comment]
Fixed by https://github.com/VLL-HD/FrEIA/pull/53

**Pull request closed without merging**
